---
name: CI

on:
  pull_request:
  # Every Monday at 4:00 UTC
  schedule:
    - cron: "0 4 * * 1"

concurrency:
  # yamllint disable-line rule:line-length
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        file:
          - onju-voice
          - onju-voice-microwakeword
        esphome-version:
          - latest
          - beta
          - dev
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.2.2
      - name: 🔨 Build firmware - ${{ matrix.esphome-version }}
        uses: esphome/build-action@v4.0.1
        with:
          yaml-file: esphome/${{ matrix.file }}.yaml
          version: ${{ matrix.esphome-version }}
